export const DO_BILL_PAY            = "DO_BILL_PAY";
export const REQUEST_REPRESENTATIVE = "REQUEST_REPRESENTATIVE";
export const TXFR_FROM_CHECKING     = "TXFR_FROM_CHECKING";
export const TXFR_FROM_SAVINGS      = "TXFR_FROM_SAVINGS";
